### ISSUE TITLE
Leaderboard- Code review

### ISSUE THREAD

**Issue by DelhinRharl** [cwaku/Leaderboard#8]
# Hi there!

You have done a great job so far. You have:

- [x] Implemented the functionalities well
- [x] The project is well styled.
 
Please check on the display viewport height of the page. 

## Thank you!

**Comment by cwaku** [comment]
Thank you for the review. Changes have been implemented. Please do take another look when you are free

**Comment by DelhinRharl** [comment]
# Good Job 👍🏽
